title: GeoWorks
url: https://www.sla.gov.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#3e6f60"
  secondary-color: "#b23954"
  media-colors:
    - title: media-color-one
      color: "#1766a0"
    - title: media-color-two
      color: "#1766a0"
    - title: media-color-three
      color: "#1766a0"
    - title: media-color-four
      color: "#1766a0"
    - title: media-color-five
      color: "#1766a0"
description: GeoWorks - Southeast Asia’s first geospatial industry centre
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d29j1jteekkr60.amplifyapp.com
prod: https://master.d29j1jteekkr60.amplifyapp.com
facebook-pixel: ""
shareicon: /images/isomer-logo.svg
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
